//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAllowance
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
